# yaml-language-server: $schema=https://json-schema.axonivy.com/config/14.0.0/databases.json
Databases:
  ivyTeamDatabase:
    Url: jdbc:mysql://ivyteam.io:3306/ivyteam
    Driver: com.mysql.cj.jdbc.Driver
    UserName: ivy
    Password: ${decrypt:/ONFjKtA0h6caXsEaRP29A==}
    MaxConnections: 10
    Properties:
      additionalPropertyName0: additionalPropertyValue0
      additionalPropertyName1: additionalPropertyValue1
  axonIvyDatabase:
    Url: jdbc:hsqldb:mem:axonivy
    Driver: org.hsqldb.jdbc.JDBCDriver
    UserName: admin
    Password: ${decrypt:k1GmwSEiJtUbRb2q6CZ9QQ==}
    MaxConnections: 42
  IvySystemDatabase:
    Url: jdbc:mysql://localhost
    Driver: com.mysql.cj.jdbc.Driver
    Password: ${decrypt:}
    MaxConnections: 5
